/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package io.blocko.pikkle.common.utilities;

import io.blocko.pikkle.common.LinkedList;

public class StringUtils {
    public static String join(LinkedList source) {
        return JoinUtils.join(source);
    }

    public static LinkedList split(String source) {
        return SplitUtils.split(source);
    }
}
