/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package io.blocko.pikkle.vote;

import org.junit.jupiter.api.Assertions;
import org.junit.jupiter.api.Test;

import static org.junit.jupiter.api.Assertions.assertEquals;

public class MessageUtilsTest {
    @Test public void testGetMessage() {
        Assertions.assertEquals("Hello      World!", MessageUtils.getMessage());
    }
}
